### ISSUE TITLE
while im downloading open images for human hands. im encountering with this error

### ISSUE THREAD

**Issue by maniteja-kamsali** [monocongo/openimages#15]
Traceback (most recent call last):
  File "c:\users\mani\appdata\local\programs\python\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\mani\appdata\local\programs\python\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\MANI\openimages\Scripts\oi_download_images.exe\__main__.py", line 7, in <module>
  File "c:\users\mani\openimages\lib\site-packages\openimages\download.py", line 850, in _entrypoint_download_images
    download_images(
  File "c:\users\mani\openimages\lib\site-packages\openimages\download.py", line 250, in download_images
    image_directories = download_dataset(
  File "c:\users\mani\openimages\lib\site-packages\openimages\download.py", line 133, in download_dataset
    label_codes = _class_label_codes(class_labels, csv_dir)
  File "c:\users\mani\openimages\lib\site-packages\openimages\download.py", line 94, in _class_label_codes
    df_classes.loc[df_classes[1] == class_label].values[0][0]
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by GrantPerkins** [comment]
Further specified in #18

**Comment by GrantPerkins** [comment]
@monocongo this should be resolved by #20. This was the same issue as #18.

**Comment by monocongo** [comment]
Thanks again for your help, @GrantPerkins 

@maniteja-kamsali if this isn't fixed by #20 then feel free to re-open the issue
